theme: jekyll-theme-minimal
title: David Kaindlstorfer
url                      : https://david-kaindls.github.io 
baseurl                  : ""
repository               : "david-kaindls.github.io"

author:
  # Biographic information
  avatar           : "avatar.jpg"
  name             : "David Kaindlstorfer"
  bio              : "PhD student at Rigorous Software Engineering Group under supervision of *Maria Christakis*"
  location         : "Vienna, AT"
  employer         : "TU Wien"
  email            : "david.kaindlstorfer@tuwien.ac.at" 
